import type { Shipment } from "./types";

export const sampleShipments: Shipment[] = [
  {
    id: "RM-1001",
    customer: "Northstar Retail",
    origin: "Shenzhen CN",
    destination: "Los Angeles CA",
    mode: "Ocean",
    carrier: "Maersk",
    plannedShipDate: "2026-05-10",
    eta: "2026-06-03",
    priority: "critical",
    value: 128000,
    skuGroup: "Electronics",
    destinationLocation: "LA DC",
  },
  {
    id: "RM-1002",
    customer: "Helio Parts",
    origin: "Hamburg DE",
    destination: "Chicago IL",
    mode: "Ocean+Rail",
    carrier: "Hapag-Lloyd",
    plannedShipDate: "2026-05-11",
    eta: "2026-06-08",
    priority: "high",
    value: 76000,
    skuGroup: "Industrial Components",
    destinationLocation: "Chicago Hub",
  },
  {
    id: "RM-1003",
    customer: "Evergreen Home",
    origin: "Savannah GA",
    destination: "Dallas TX",
    mode: "Truck",
    carrier: "JB Hunt",
    plannedShipDate: "2026-05-20",
    eta: "2026-05-25",
    priority: "standard",
    value: 18500,
    skuGroup: "Furniture",
    destinationLocation: "Dallas DC",
  },
  {
    id: "RM-1004",
    customer: "Arc Supply",
    origin: "Busan KR",
    destination: "Seattle WA",
    mode: "Ocean",
    carrier: "ONE",
    plannedShipDate: "2026-05-12",
    eta: "2026-06-01",
    priority: "critical",
    value: 94000,
    skuGroup: "Semiconductors",
    destinationLocation: "Seattle DC",
  },
  {
    id: "RM-1005",
    customer: "Peak Foods",
    origin: "Veracruz MX",
    destination: "Atlanta GA",
    mode: "Truck",
    carrier: "Schneider",
    plannedShipDate: "2026-05-19",
    eta: "2026-05-24",
    priority: "high",
    value: 42000,
    skuGroup: "Packaged Foods",
    destinationLocation: "Atlanta DC",
  },
];
